    <footer class="footer-container">
        <span class="blur"></span>
        <span class="blur"></span>

        <div class="column">

            <p>
                TechNova .INC <br>
                Innovation for future. 
            </p>

            <button class="media youtube"> 
                <div class="media-logo">
                    <a href="#"><i class="fa-brands fa-youtube"></i></a>
                </div> 
            </button>
            
            <button class="media facebook"> 
                <div class="media-logo">
                    <a href="https://www.facebook.com/tienhung.bui.33633"><i class="fa-brands fa-facebook"></i></a>
                </div> 
            </button>
            
            <button class="media email"> 
                <div class="media-logo">
                    <a href="mailto:tienhung2000dt@gmail.com"><i class="fa-solid fa-envelope"></i></a>
                </div> 
            </button>
            
            <button class="media github"> 
                <div class="media-logo">
                    <a href="https://github.com/THungB"><i class="fa-brands fa-github"></i></a>
                </div> 
            </button>
            
            <button class="media linkedin"> 
                <div class="media-logo">
                    <a href="https://www.linkedin.com/in/b%C3%B9i-ti%E1%BA%BFn-h%C6%B0ng-261309341/"><i class="fa-brands fa-linkedin"></i></a>
                </div> 
            </button>
                        
            <p>Copyright <i class="fa-solid fa-copyright"></i> TechNova.Inc 2025. All Rights Reserved.</p>
        </div>

        <div class="column">
            <h4>Our Team</h4>
            <a href="#">Business</a>
            <a href="#">Partnership</a>
            <a href="#">Network</a>
        </div>

        <div class="column">
            <h4>Contact</h4>
            <a href="#">Contact Us</a>
            <a href="#">Privacy Policy</a>
            <a href="#">Term & Conditions</a>
        </div>

        <div class="column">
            <h4>About Us</h4>
            <a href="#">Blogs</a>
            <a href="#">Channels</a>
            <a href="#">Sponsors</a>
        </div>

    </footer>