<section id="header" data-aos="fade-down" data-aos-duration="1500">
        <a href="index.html"><img src="images/logo.png" class="logo" alt="logo"></a>
        <div>
            <ul id="navbar">
                <li><a class="active" href="index.php">Home</a></li>
                <li><a href="jobs.php">Job Descriptions</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About Us</a></li>
                <li><a href="enhancements.php">Enhancements</a></li>
            </ul>
        </div>
        <a href="register.php">
        <button data-aos="fade-down" data-aos-duration="2000" class="btn-signing">SIGN IN</button>
        </a>
</section>